# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edward Dibbs
email: ed@eddibbs.com
description: > # this means to ignore newlines until "baseurl:"
  An online portfolio for Ed Dibbs, Software Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eddibbs.com" # the base hostname & protocol for your site
#twitter_username:
github_username:  eddibbs
google_analytics: UA-92571345-1


# Build settings
markdown: kramdown
